name = "affiliate-admin"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets" }

[vars]
NEXT_PUBLIC_BASE_URL = "https://affiliate-web.yanagiho.workers.dev"
